favicon: /img/favicon.png
# Change to your profile picture
avatar: /img/profile.jpg
# if author sets in hexo_config, this string doesn't work
author: 'Jason'
# author_bio: 'Your biography can be writed down here.'

since: 2020

# Top Menu é¡¶éƒ¨èœå•
# #title ä¸ºé¡µå†…è·³è½¬ï¼Œå•é¡µæ¨¡å¼
# å¯ä»¥é€‰æ‹©å¤–é“¾æˆ–å…¶ä»–é¡µé¢
menu:
  Education: /#ğŸ“-Education
  News: /#ğŸ”¥-News
  Publications: /#ğŸ“-Publications
  Grants: /#ğŸ›¸-Research-Grants
  Students: /#ğŸ¤“-Student-Supervision
  Services: /#ğŸ’»-Academic-Services
  Teaching: /#ğŸ‘©â€ğŸ«-Teaching-Experiences
  Honors & Awards : /#ğŸ–ï¸-Honors-Awards
  Internships : /#ğŸ› ï¸-Internships
  # Publications: /#test
  # Blog: https://phower.me

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.jpg

# Social Links; ç¤¾äº¤é“¾æ¥ï¼Œä¸éœ€è¦çš„é“¾æ¥ç›´æ¥æ³¨é‡Šæ‰
# å¯ä»¥è°ƒæ•´æ˜¾ç¤ºé¡ºåº
# å›¾æ ‡è°ƒç”¨ font-awesome 4.7
social:
  enable: false
social_links:
  # fab fa-github: /
  # fas fa-envelope: mailto:libeibeics@cqu.edu.cn/ #E-mail
  # fas fa-rss: /  #rss
  # fab fa-qq: /
  # fab fa-stack-overflow: /
  # fab fa-linkedin: /
  # fab fa-weibo: /
  # fab fa-weixin: /
  # fab fa-twitter: /
  # fab fa-facebook-square: /

# Additional social_linksï¼Œé¢å¤–æ·»åŠ è‡ªå®šä¹‰é“¾æ¥ï¼Œå¯æ˜¾ç¤ºé“¾æ¥åç§°
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: https://scholar.google.com/citations?user=ffr1yuAAAAAJ&hl=zh-CN / || fas fa-graduation-cap
  ORCID: https://orcid.org/0000-0003-2711-9370 / || fab fa-orcid
  libeibeics@cqu.edu.cn: mailto:libeibeics@cqu.edu.cn / || fas fa-envelope

# CV download link
cv_dl:
  enable: false
  dir: /
  description: .
  # dir: /attaches/CV.pdf
  # description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# æ ¹æ®éœ€è¦è‡ªè¡Œæ·»åŠ js/css
# è‡ªå®šä¹‰csså¯ä»¥ç›´æ¥å†™åœ¨user.stylä¸­
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js